[workspace]
resolver = "3"
members = [
	"apps/common",
	"apps/gym",
	"apps/test",
	"common",
	"host",
	"modules/all",
	"modules/calendar",
	"modules/common",
	"modules/execute",
	"modules/show",
	"utils/db",
	"utils/time",
]

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
anyhow = "1.0.104"
chrono = { version = "0.4.45", features = ["serde"] }

common.path = "./common"
host.path = "./host"

util_db.path = "./utils/db"
util_time.path = "./utils/time"

module_common.path = "./modules/common"
module_execute.path = "./modules/execute"
module_calendar.path = "./modules/calendar"
module_show.path = "./modules/show"
modules.path = "./modules/all"

app_common.path = "./apps/common"
app_test.path = "./apps/test"
app_gym.path = "./apps/gym"
